declare const styles: {
  readonly "catpolColorPrimary": string;
  readonly "catpolColorSecondary": string;
  readonly "catpolColorAuxDark": string;
  readonly "catpolButton": string;
  readonly "catpolButtonPrimary": string;
  readonly "catpolButtonSecondary": string;
  readonly "catpolRow": string;
  readonly "catpolColOffset1": string;
  readonly "catpolColOffset2": string;
  readonly "catpolColOffset3": string;
  readonly "catpolColOffset4": string;
  readonly "catpolColOffset5": string;
  readonly "catpolColOffset6": string;
  readonly "catpolColOffset7": string;
  readonly "catpolColOffset8": string;
  readonly "catpolColOffset9": string;
  readonly "catpolColOffset10": string;
  readonly "catpolColOffset11": string;
  readonly "catpolColOffset12": string;
  readonly "catpolCol1": string;
  readonly "catpolCol2": string;
  readonly "catpolCol3": string;
  readonly "catpolCol4": string;
  readonly "catpolCol5": string;
  readonly "catpolCol6": string;
  readonly "catpolCol7": string;
  readonly "catpolCol8": string;
  readonly "catpolCol9": string;
  readonly "catpolCol10": string;
  readonly "catpolCol11": string;
  readonly "catpolCol12": string;
  readonly "hideSmall": string;
  readonly "hideLarge": string;
  readonly "catpolFlexCenter": string;
};
export = styles;

